# Reverse Dependency checks

## r-lib::revdepcheck

Works relatively well and seems to use the binaries.  Can also specify number of
workers directly.  Just requires a lot of packages, including non-CRAN ones.

Additionally, it needs to install everything from source if running in docker,
so takes a while to even get `revdepcheck` setup.  Not sure if we can avoid
source install in docker?  We should be able with Maruter or the Rstudio
repo, but at least Maruter is only 4.0 (but shouldn't matter for revdeps,
unless we get unlucky with a bad interaction)?

Update: we ran in the Rocker `rspm` container and that seemed to help.  We also
tried with `bspm`, but ran into (possibly `revdepcheck` issues) and switched to
see it would help (not clear that it did, not sure).

Overall the experience was not ideal.  It seemed to work okay for some set of
packages, but then it would get in a state where it would fail to run the tests,
and simply pretend everything was fine.

One of the reasons why this happened was the timeout, and possibly [crancache
getting confused](https://github.com/r-lib/revdepcheck/issues/213).  Using:

```
revdepcheck::revdep_check(num_workers = 2, timeout = as.difftime(360,units = "mins"))
```

Helped for some, but not all.

Eventually, had to manually run some myself (3 or 4 packages).

Additionally, if there are install failures or whatever, `revdepcheck` will
report everything is fine because failures happened in both original version of
package and new one, which is silly.  It doesn't check against CRAN.

> See revdep-docker.Rmd, and bspm comments later in this page.

## Manual Approach

[Mark's Blog](https://www.markvanderloo.eu/yaRb/2019/04/26/checking-reverse-dependencies-the-tiny-way/).

There is a bug in 4.0.3 that means this doesn't work (at least with
`reverse=list(which='most')` (no, this persists even with the empty list)?.

```
result <- tools::check_packages_in_dir(".", reverse = list())
# # most includes suggests, but it seems like it downloads all their recursive
# # suggests too?
result <- tools::check_packages_in_dir(".", reverse = list(which='most'))
summary(result)
```

Main issue we've run into is that automatic rev dep install is from sources,
which is a pain because in many cases source builds require system libraries to
be present.  We do need source packages for what's being tested, but we should
be able to install other stuff from binaries.

Question: does `tools::check_packages_in_dir` insist on installing all recursive
dependencies even when present?  Seems like it does.  It's not satisfied with
with checking whether something is already in the library.  It always
re-installs everything from source.

**However**, if we can bear the time it takes to do this it is okay because the
installs from binary will still be present and work after the installs from
source fails.

So tentative ideal process is:

1. Collect all our reverse imports / depends / (suggests)
2. Collect all their reverse imports etc.
3. Install all of (2.) from binaries in "./Library".  `check_packages_in_dir`
   will try to install all these again fresh, but even if they fail re-install
   it will be fine because they are present in the library.
4. Remove all old checks `rm -r *.Rcheck`
5. Run `result <- tools::check_packages_in_dir(".", reverse = list())`

Need to adapt it to see if we can do all of this in docker image to mitigate the
risk of someone maliciously adding a suggests.

Testing to see if we can install test with binary; don't recall what happened
here.

## Getting revdeps

```
pkg <- 'fansi'
db <- tools::CRAN_package_db()
# dtype <- c('depends', 'imports', 'suggests', 'linking to')
dtype <- c('depends', 'imports', 'linking to')
deps <- unlist(subset(db, Package == pkg)[paste0('Reverse ', dtype)])
bad <- c('mimic.demo', 'eicu.demo')
base <- c(
  "R", "base", "compiler", "datasets", "grDevices", "graphics",
  "grid", "methods", "parallel", "profile", "splines", "stats",
  "stats4", "tcltk", "tools", "utils"
)
clean_name <- function(x) {
  tmp <- unique(trimws(gsub("\\(.*\\)$", "", x)))
  tmp[!tmp %in% c(base, bad)]
}

rev <- unname(unlist(strsplit(deps[!is.na(deps)], ", ")))
## install.packages(
##   rev, lib='./Library', repos='https://cloud.r-project.org', type="both",
##   INSTALL_opts="--install-tests"
## )

## Things that didn't install
rev[!rev %in% rownames(installed.packages())]

deps.rev <- unlist(
  subset(db, Package %in% rev)[
    paste0(c('Depends', 'Imports', 'Suggests', 'LinkingTo'))
  ]
)
rev.rev <- unname(unlist(strsplit(deps.rev[!is.na(deps.rev)], ",[ \n]*")))
rev.rev <- clean_name(rev.rev)
rev.rev <- rev.rev[!rev.rev == 'R']


# this was from a lazy run for diffobj where we tried dumbly first, and saw the
# failed packages
rev.rev <- c('keyring', 'sf', 'tigris', 'rgeos')
install.packages(
  rev.rev, lib='./Library', repos='https://cloud.r-project.org', type="binary"
)

```

## Docker Container

Commentary from Dirk on how to get started:

> If I were to go that route I would either start from r-base (plain Debian,
> usually in a good state) or with rocker/r-bspm:20.04 (Ubuntu, with 'automagic'
> use of Rutter PPAs via bspm).  More people more at ease with the
> market-leading supplier of all things there is also rocker/r-rspm:20.04
> (Ubuntu plus RSPM; no provision for sys.deps because, well, bspm does that
> already, and better).

The BSPM thing looks like it's really what we want[1] as it resolves the system
dependency issue, although does it work with r-devel?  I guess we don't need to
do the revdeps on r-devel, although it is possible it could be a problem.

We ended up giving up on this because it didn't seem to work well with
`revdepcheck`, but it could just have been `revdepcheck` acting up.

See revdep-docker.Rmd.

## r2u

There is now also [r2u][2].

[1]: https://dirk.eddelbuettel.com/blog/2020/08/26/


